;input 0-6/output day corresponding
.ORIG x3000	
RESTART	LEA R0, PROMPT		;LOADS PROMPT MESSAGE
	PUTS			;WHOS MESSAGE ON CONSOLE
	GETC			;READS IN CHAR
	ADD R3, R0, X0		;COPY R0 TO R3
	ADD R3, R3, #-16	;Offset by 16 for ascii
	ADD R3, R3, #-16	;OFFSET BY 16, TOTAL 32
	ADD R3, R3, #-16	;OFFSET BY 16, TOTAL 48
	ADD R4, R3, #-6		;INPUT VALIDATION
	BRp ERROR		;GOES TO ERROR IF INVALID INPUT
	LEA R0, DAYS		;LOADS DAYS TO R0
	ADD R3, R3, X0 		;ZERO BRANCHING
LOOP	BRz DISPLAY		;LOOP LABLE, IF 0, GO TO DISPLAY
	ADD R0, R0, #10		;FILL REGISTER WITH MAX CHARACTERS
	ADD R3, R3, #-1		;REDUCES BY ONE, GOING TO NEXT DAY
	BR LOOP			;GO TO LOOP
DISPLAY PUTS			;SHOW ON SCREEN
	LEA R0, LF		;LOAD LF, HOLDS DAYS AS STRING
	PUTS			;SHOW ON SCREEN
	BR RESTART		;GO BACK TO PROMPT
ERROR	LEA R0, ERMS		;LOADS ERROR MESSAGE FOR INVALID INPUT
	PUTS			;DISPLAYS MESSAGE3
	HALT			;STOPS PROGRAM

;DATA

PROMPT	.STRINGZ	"PLEASE ENTER NUMBER 0 - 6: "
DAYS	.STRINGZ	"SUNDAY   "
	.STRINGZ	"MONDAY   "
	.STRINGZ	"TUESDAY  "
	.STRINGZ	"WEDNESDAY"
	.STRINGZ	"THURSDAY "
	.STRINGZ	"FRIDAY   "
	.STRINGZ	"SATURDAY "
ERMS	.STRINGZ	"INVALID INPUT"
LF	.FILL X000A

.END